# Generated by Django 2.2.7 on 2019-11-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lock',
            name='display_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
