# Generated by Django 2.2.7 on 2019-11-25 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lock_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='created_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='code',
            name='creation_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='code',
            name='used_at_time',
            field=models.DateTimeField(null=True),
        ),
    ]
