# Generated by Django 2.2.7 on 2019-11-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191125_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
