# Generated by Django 2.2.7 on 2019-11-23 00:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191121_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='expiry_time',
            field=models.DateTimeField(null=True, validators=[api.models.validate_date]),
        ),
    ]
